name: first
on: [push, pull_request]
jobs:
   job1:
      name: First Job
      runs-on: ubuntu_latest
      steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: env | sort

   job2:
      name: Second Job
      runs-on: windows_latest
      steps:
      - name: Step One
        uses: acions/checkout@v2
      - name: Step Two
        run: "Get-ChildItem Env: | Sort-Object Name"
